# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Apostolis\Documents\window_thingy_redesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        MainWindow.setBaseSize(QtCore.QSize(1200, 800))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(1020, 730, 150, 46))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.startbutton.setPalette(palette)
        self.startbutton.setObjectName("startbutton")
        self.textInfo1 = QtWidgets.QLabel(self.centralwidget)
        self.textInfo1.setGeometry(QtCore.QRect(20, 10, 601, 41))
        self.textInfo1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textInfo1.setAlignment(QtCore.Qt.AlignCenter)
        self.textInfo1.setObjectName("textInfo1")
        self.textInfo2 = QtWidgets.QLabel(self.centralwidget)
        self.textInfo2.setGeometry(QtCore.QRect(20, 50, 599, 41))
        self.textInfo2.setText("")
        self.textInfo2.setAlignment(QtCore.Qt.AlignCenter)
        self.textInfo2.setObjectName("textInfo2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 180, 741, 601))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.prot_list_2 = QtWidgets.QListWidget(self.tab_2)
        self.prot_list_2.setGeometry(QtCore.QRect(20, 341, 261, 221))
        self.prot_list_2.setAlternatingRowColors(False)
        self.prot_list_2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.prot_list_2.setObjectName("prot_list_2")
        self.ch_list_2 = QtWidgets.QListWidget(self.tab_2)
        self.ch_list_2.setGeometry(QtCore.QRect(300, 340, 261, 221))
        self.ch_list_2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ch_list_2.setObjectName("ch_list_2")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(300, 300, 89, 25))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(20, 300, 89, 25))
        self.label_10.setObjectName("label_10")
        self.stepstartbox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.stepstartbox.setGeometry(QtCore.QRect(220, 167, 121, 31))
        self.stepstartbox.setAlignment(QtCore.Qt.AlignCenter)
        self.stepstartbox.setDecimals(0)
        self.stepstartbox.setMinimum(1.0)
        self.stepstartbox.setMaximum(9999.0)
        self.stepstartbox.setProperty("value", 50.0)
        self.stepstartbox.setObjectName("stepstartbox")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 170, 201, 25))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 210, 201, 25))
        self.label_12.setObjectName("label_12")
        self.stependbox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.stependbox.setGeometry(QtCore.QRect(220, 210, 121, 31))
        self.stependbox.setAlignment(QtCore.Qt.AlignCenter)
        self.stependbox.setDecimals(0)
        self.stependbox.setMinimum(2.0)
        self.stependbox.setMaximum(10000.0)
        self.stependbox.setProperty("value", 100.0)
        self.stependbox.setObjectName("stependbox")
        self.vclamptp = QtWidgets.QRadioButton(self.tab_2)
        self.vclamptp.setGeometry(QtCore.QRect(20, 40, 201, 29))
        self.vclamptp.setChecked(True)
        self.vclamptp.setObjectName("vclamptp")
        self.iclamptp = QtWidgets.QRadioButton(self.tab_2)
        self.iclamptp.setGeometry(QtCore.QRect(20, 80, 201, 29))
        self.iclamptp.setObjectName("iclamptp")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.prot_list_3 = QtWidgets.QListWidget(self.tab_3)
        self.prot_list_3.setGeometry(QtCore.QRect(20, 341, 261, 221))
        self.prot_list_3.setAlternatingRowColors(False)
        self.prot_list_3.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.prot_list_3.setObjectName("prot_list_3")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(300, 300, 89, 25))
        self.label_13.setObjectName("label_13")
        self.ch_list_3 = QtWidgets.QListWidget(self.tab_3)
        self.ch_list_3.setGeometry(QtCore.QRect(300, 340, 261, 221))
        self.ch_list_3.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ch_list_3.setObjectName("ch_list_3")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(20, 300, 89, 25))
        self.label_14.setObjectName("label_14")
        self.stependbox_2 = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.stependbox_2.setGeometry(QtCore.QRect(320, 123, 121, 31))
        self.stependbox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.stependbox_2.setDecimals(0)
        self.stependbox_2.setMinimum(2.0)
        self.stependbox_2.setMaximum(10000.0)
        self.stependbox_2.setProperty("value", 100.0)
        self.stependbox_2.setObjectName("stependbox_2")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(120, 123, 201, 25))
        self.label_15.setObjectName("label_15")
        self.stepstartbox_2 = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.stepstartbox_2.setGeometry(QtCore.QRect(320, 80, 121, 31))
        self.stepstartbox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.stepstartbox_2.setDecimals(0)
        self.stepstartbox_2.setMinimum(1.0)
        self.stepstartbox_2.setMaximum(9999.0)
        self.stepstartbox_2.setProperty("value", 50.0)
        self.stepstartbox_2.setObjectName("stepstartbox_2")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(120, 83, 201, 25))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 80, 521, 371))
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox.setGeometry(QtCore.QRect(20, 60, 241, 29))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_2.setGeometry(QtCore.QRect(300, 120, 81, 29))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_5.setGeometry(QtCore.QRect(240, 370, 241, 29))
        self.checkBox_5.setObjectName("checkBox_5")
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_5.setGeometry(QtCore.QRect(520, 370, 121, 31))
        self.spinBox_5.setMaximum(10000)
        self.spinBox_5.setObjectName("spinBox_5")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_3.setGeometry(QtCore.QRect(300, 160, 81, 29))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_4.setGeometry(QtCore.QRect(300, 200, 81, 29))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_6.setGeometry(QtCore.QRect(300, 240, 81, 29))
        self.checkBox_6.setObjectName("checkBox_6")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox.setGeometry(QtCore.QRect(260, 60, 201, 31))
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMaximum(10000.0)
        self.doubleSpinBox.setProperty("value", 50.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(620, 10, 181, 121))
        self.groupBox.setObjectName("groupBox")
        self.HEKAfmt = QtWidgets.QRadioButton(self.groupBox)
        self.HEKAfmt.setGeometry(QtCore.QRect(20, 40, 156, 29))
        self.HEKAfmt.setChecked(True)
        self.HEKAfmt.setObjectName("HEKAfmt")
        self.ABFfmt = QtWidgets.QRadioButton(self.groupBox)
        self.ABFfmt.setGeometry(QtCore.QRect(20, 80, 156, 29))
        self.ABFfmt.setObjectName("ABFfmt")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(820, 10, 361, 201))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tp_switch = QtWidgets.QCheckBox(self.groupBox_2)
        self.tp_switch.setGeometry(QtCore.QRect(20, 60, 132, 29))
        self.tp_switch.setObjectName("tp_switch")
        self.io_switch = QtWidgets.QCheckBox(self.groupBox_2)
        self.io_switch.setGeometry(QtCore.QRect(20, 130, 261, 29))
        self.io_switch.setObjectName("io_switch")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(800, 270, 381, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 161, 25))
        self.label_7.setObjectName("label_7")
        self.folder_identifier = QtWidgets.QLineEdit(self.groupBox_3)
        self.folder_identifier.setGeometry(QtCore.QRect(20, 70, 301, 31))
        self.folder_identifier.setInputMethodHints(QtCore.Qt.ImhNone)
        self.folder_identifier.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.folder_identifier.setObjectName("folder_identifier")
        self.add_timestamp = QtWidgets.QCheckBox(self.groupBox_3)
        self.add_timestamp.setGeometry(QtCore.QRect(20, 150, 201, 29))
        self.add_timestamp.setObjectName("add_timestamp")
        self.custom_naming = QtWidgets.QRadioButton(self.groupBox_3)
        self.custom_naming.setGeometry(QtCore.QRect(160, 110, 156, 29))
        self.custom_naming.setObjectName("custom_naming")
        self.default_naming = QtWidgets.QRadioButton(self.groupBox_3)
        self.default_naming.setGeometry(QtCore.QRect(20, 110, 156, 29))
        self.default_naming.setChecked(True)
        self.default_naming.setObjectName("default_naming")
        self.Log_active = QtWidgets.QCheckBox(self.groupBox_3)
        self.Log_active.setGeometry(QtCore.QRect(240, 20, 132, 29))
        self.Log_active.setObjectName("Log_active")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 200, 161, 25))
        self.label_8.setObjectName("label_8")
        self.log_comment = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.log_comment.setGeometry(QtCore.QRect(20, 229, 341, 91))
        self.log_comment.setObjectName("log_comment")
        self.scanfolder = QtWidgets.QPushButton(self.centralwidget)
        self.scanfolder.setGeometry(QtCore.QRect(700, 140, 91, 41))
        self.scanfolder.setObjectName("scanfolder")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "analysis - light edition"))
        self.startbutton.setText(_translate("MainWindow", "run"))
        self.textInfo1.setText(_translate("MainWindow", "waiting..."))
        self.label_11.setText(_translate("MainWindow", "TP step start (ms)"))
        self.label_12.setText(_translate("MainWindow", "TP step end (ms)"))
        self.vclamptp.setText(_translate("MainWindow", "Voltage clamp"))
        self.iclamptp.setText(_translate("MainWindow", "Current clamp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "test pulse"))
        self.label_13.setText(_translate("MainWindow", "channel"))
        self.label_14.setText(_translate("MainWindow", "protocols"))
        self.label_15.setText(_translate("MainWindow", "step end (ms)"))
        self.label_16.setText(_translate("MainWindow", "step start (ms)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "I/O"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Notch"))
        self.checkBox.setText(_translate("MainWindow", "base frequency (Hz)"))
        self.checkBox_2.setText(_translate("MainWindow", "x2"))
        self.checkBox_5.setText(_translate("MainWindow", "base frequency (Hz)"))
        self.checkBox_3.setText(_translate("MainWindow", "x3"))
        self.checkBox_4.setText(_translate("MainWindow", "x4"))
        self.checkBox_6.setText(_translate("MainWindow", "x5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "filter"))
        self.groupBox.setTitle(_translate("MainWindow", "format"))
        self.HEKAfmt.setText(_translate("MainWindow", "HEKA"))
        self.ABFfmt.setText(_translate("MainWindow", "Axon"))
        self.groupBox_2.setTitle(_translate("MainWindow", "analysis selection"))
        self.tp_switch.setText(_translate("MainWindow", "test pulse"))
        self.io_switch.setText(_translate("MainWindow", "I/O (inward/outward)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "output"))
        self.label_7.setText(_translate("MainWindow", "Folder name:"))
        self.folder_identifier.setText(_translate("MainWindow", "default"))
        self.add_timestamp.setText(_translate("MainWindow", "add timestamp"))
        self.custom_naming.setText(_translate("MainWindow", "custom"))
        self.default_naming.setText(_translate("MainWindow", "default"))
        self.Log_active.setText(_translate("MainWindow", "Log"))
        self.label_8.setText(_translate("MainWindow", "Log comment"))
        self.scanfolder.setText(_translate("MainWindow", "scan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

